import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import Box from '@mui/material/Box';
// import Stack from '@mui/material/Stack';
import { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { getMonsInfo } from '../redux/monsInfoSlice'

export default function MonsList () {

  const [mons, setMons] = useState(null)
  // const [mons, setMons] = useState({
  //   name: '',
  //   family: '',
  //   element: '',
  // })
  const dispatch = useDispatch()

  useEffect( ()=> {
    if (mons) {
      const name = mons.name
      const index = mons.index
      // const index = mons.index ?? null
      // console.log('[MonsList]: ', mons);
      dispatch(getMonsInfo({name, index}))

    }
  }, [mons])

  return (
    <Box sx={{mb:2}}>
      <Autocomplete
        clearOnEscape
        blurOnSelect
        noOptionsText={'No results found'}
        options={monsList}
        // getOptionLabel={(option) => option.name}
        getOptionLabel={(option) => (
          option.name + (option.form ?? '') + ' -- ' + option.family + ' (' + option.element + ')'
        )}
        value={mons}
        onChange={(event, newValue) => setMons(newValue)}
        renderInput={(params) => (
          <TextField {...params} label="Select monster" variant="standard" />
        )}
      />
    </Box>
  )
}

const monsList  = [
  // { name: 'Seara', family: 'Oracle', element: 'Wind' },
  // { name: 'Dominic', family: 'Weapon Master', element: 'Wind' },
  // { name: 'Barbara', family: 'Beast Rider', element: 'Water' },
  // { name: 'Masha', family: 'Beast Rider', element: 'Fire' },
  // { name: 'Savannah', family: 'Beast Rider', element: 'Wind' },
  // // { name: 'Dominic' },
  { name: 'Aaliyah', family: 'Totemist', element: 'Water' },
  { name: 'Abellio', family: 'Druid', element: 'Water' },
  { name: 'Abellio', family: 'Druid', element: 'Water', form: ' (Beast)', index: 1 },
  { name: 'Abigail', family: 'Cannon Girl', element: 'Water' },
  { name: 'Acasis', family: 'Sylphid', element: 'Wind' },
  { name: 'Adrian', family: 'Elven Ranger', element: 'Fire' },
  { name: 'Adriana', family: 'Pudding Princess', element: 'Water' },
  { name: 'Aegir', family: 'Barbaric King', element: 'Water' },
  { name: 'Aeilene', family: 'Fairy', element: 'Wind' , index: 1},
  { name: 'Ahman', family: 'Bearman', element: 'Light' },
  { name: 'Akhamamir', family: 'Ifrit', element: 'Wind' },
  { name: 'Akia', family: 'Succubus', element: 'Fire' },
  { name: 'Akroma', family: 'Valkyrja', element: 'Light' },
  { name: 'Alexandra', family: 'Unicorn', element: 'Dark' },
  { name: 'Alexandra', family: 'Unicorn', element: 'Dark', form: ' (Human)', index: 1 },
  { name: 'Alice', family: 'Macaron Guard', element: 'Fire' },
  { name: 'Alicia', family: 'Polar Queen', element: 'Water' },
  { name: 'Allen', family: 'Vagabond', element: 'Water', index: 1 },
  { name: 'Amarna', family: 'Anubis', element: 'Light' },
  { name: 'Amber', family: 'Battle Angel', element: 'Water' },
  { name: 'Amduat', family: 'Horus', element: 'Dark' },
  { name: 'Amelia', family: 'Unicorn', element: 'Water' },
  { name: 'Amelia', family: 'Unicorn', element: 'Water', form: ' (Human)', index: 1 },
  { name: 'Anavel', family: 'Occult Girl', element: 'Water' },
  { name: 'Anduril', family: 'Inferno', element: 'Wind' },
  { name: 'Angela', family: 'Pudding Princess', element: 'Wind' },
  { name: 'Anne', family: 'Cow Girl', element: 'Fire' },
  { name: 'Antares', family: 'Lich', element: 'Fire' },
  { name: 'Aqcus', family: 'Charger Shark', element: 'Water' },
  { name: 'Aquila', family: 'Brownie Magician', element: 'Wind' },
  { name: 'Arang', family: 'Nine-tailed Fox', element: 'Wind' },
  { name: 'Ardella', family: 'Magical Archer', element: 'Wind' },
  { name: 'Argen', family: 'Vampire', element: 'Wind' },
  { name: 'Aria', family: 'Succubus', element: 'Light' },
  { name: 'Ariana', family: 'Pudding Princess', element: 'Light' },
  { name: 'Ariel', family: 'Archangel', element: 'Water' },
  { name: 'Arkajan', family: 'Yeti', element: 'Light' },
  { name: 'Arnold', family: 'Death Knight', element: 'Fire' },
  { name: 'Artamiel', family: 'Archangel', element: 'Light' },
  { name: 'Aschubel', family: 'Sylph', element: 'Dark' },
  { name: 'Asima', family: 'Hell Lady', element: 'Light' },
  { name: 'Astar', family: 'Magic Knight', element: 'Fire' },
  { name: 'Atenai', family: 'Undine', element: 'Fire' },
  { name: 'Audrey', family: 'Macaron Guard', element: 'Light' },
  { name: 'Avaris', family: 'Anubis', element: 'Water' },
  { name: 'Baekdu', family: 'Beast Hunter', element: 'Light' },
  { name: 'Bael', family: 'Demon', element: 'Fire' },
  { name: 'Bagir', family: 'Giant Warrior', element: 'Water' },
  { name: 'Bailey', family: 'Boomerang Warrior', element: 'Light' },
  { name: 'Baleygr', family: 'Lightning Emperor', element: 'Fire' },
  { name: 'Barbara', family: 'Beast Rider', element: 'Water' },
  { name: 'Barbara', family: 'Beast Rider', element: 'Water', form: ' (Dismounted)', index: 1 },
  { name: 'Baretta', family: 'Sylph', element: 'Fire' },
  { name: 'Barque', family: 'Pirate Captain', element: 'Wind' },
  { name: 'Basalt', family: 'Battle Mammoth', element: 'Dark' },
  { name: 'Bastet', family: 'Desert Queen', element: 'Water' },
  { name: 'Beelzebub', family: 'Demon', element: 'Dark' },
  { name: 'Belial', family: 'Demon', element: 'Water' },
  { name: 'Belita', family: 'Chakram Dancer', element: 'Dark' },
  { name: 'Bella', family: 'Cannon Girl', element: 'Dark' },
  { name: 'Belladeon', family: 'Inugami', element: 'Light', index: 1 },
  { name: 'Bellenus', family: 'Druid', element: 'Fire'},
  { name: 'Bellenus', family: 'Druid', element: 'Fire', form: ' (Beast)', index: 1 },
  { name: 'Benedict', family: 'Weapon Master', element: 'Light' },
  { name: 'Berenice', family: 'Blade Dancer', element: 'Fire' },
  { name: 'Bering', family: 'Kobold Bomber', element: 'Dark' },
  { name: 'Bernadotte', family: 'Shadow Claw', element: 'Fire' },
  { name: 'Bernard', family: 'Griffon', element: 'Wind', index: 1 },
  { name: 'Beth', family: 'Hell Lady', element: 'Water' },
  { name: 'Bethony', family: 'Magical Archer', element: 'Dark' },
  { name: 'Betta', family: 'Mermaid', element: 'Dark' },
  { name: 'Birman', family: 'Hypnomeow', element: 'Water' },
  { name: 'Bolverk', family: 'Lightning Emperor', element: 'Water' },
  { name: 'Bombay', family: 'Hypnomeow', element: 'Dark' },
  { name: 'Borgnine', family: 'Slayer', element: 'Water' },
  { name: 'Brandia', family: 'Polar Queen', element: 'Fire' },
  { name: 'Bremis', family: 'Elemental', element: 'Fire' },
  { name: 'Briand', family: 'Death Knight', element: 'Wind' },
  { name: 'Brig', family: 'Pirate Captain', element: 'Light' },
  { name: 'Bulldozer', family: 'Frankenstein', element: 'Fire' },
  { name: 'Burentau', family: 'Minotauros', element: 'Fire' },
  { name: 'Cadiz', family: 'Vampire', element: 'Dark' },
  { name: 'Cahule', family: 'Garuda', element: 'Fire' },
  { name: 'Calicus', family: 'Charger Shark', element: 'Dark' },
  { name: 'Camaryn', family: 'Pixie', element: 'Dark', index: 1 },
  { name: 'Camilla', family: 'Valkyrja', element: 'Water' },
  { name: 'Camules', family: 'Elemental', element: 'Dark' },
  { name: 'Carbine', family: 'Sniper Mk.I', element: 'Wind' },
  { name: 'Carcano', family: 'Sniper Mk.I', element: 'Fire' },
  { name: 'Carlos', family: 'Weapon Master', element: 'Fire' },
  { name: 'Carrack', family: 'Pirate Captain', element: 'Fire' },
  { name: 'Cassandra', family: 'Magical Archer', element: 'Fire' },
  { name: 'Cassie', family: 'Cow Girl', element: 'Dark' },
  { name: 'Cayde', family: 'Poison Master', element: 'Dark' },
  { name: 'Celia', family: 'Harp Magician', element: 'Light' },
  { name: 'Celine', family: 'Rune Blacksmith', element: 'Wind' },
  { name: 'Ceres', family: 'Amazon', element: 'Fire' },
  { name: 'Chacha', family: 'Howl', element: 'Dark', index: 1 },
  { name: 'Chamie', family: 'Nine-tailed Fox', element: 'Light' },
  { name: 'Chamomile', family: 'Black Tea Bunny', element: 'Wind' },
  { name: 'Chandra', family: 'Beast Monk', element: 'Water' },
  { name: 'Charlotte', family: 'Occult Girl', element: 'Wind' },
  { name: 'Chasun', family: 'Sky Dancer', element: 'Wind' },
  { name: 'Cheongpung', family: 'Art Master', element: 'Wind' },
  { name: 'Cheryl', family: 'Pixie', element: 'Light', index: 1 },
  { name: 'Chichi', family: 'Howl', element: 'Wind', index: 1 },
  { name: 'Chilling', family: 'Jack-o’-lantern', element: 'Water' },
  { name: 'Chiwu', family: 'Pioneer', element: 'Fire' },
  { name: 'Chloe', family: 'Epikion Priest', element: 'Fire' },
  { name: 'Chow', family: 'Dragon Knight', element: 'Water' },
  { name: 'Chris', family: 'Magical Archer', element: 'Light' },
  { name: 'Christina', family: 'Cannon Girl', element: 'Wind' },
  { name: 'CHUN-LI', family: 'CHUN-LI', element: 'Dark', index: 4 },
  { name: 'CHUN-LI', family: 'CHUN-LI', element: 'Light', index: 3 },
  { name: 'CHUN-LI', family: 'CHUN-LI', element: 'Wind', index: 2 },
  { name: 'CHUN-LI', family: 'CHUN-LI', element: 'Water', index: 0 },
  { name: 'CHUN-LI', family: 'CHUN-LI', element: 'Fire', index: 1 },
  { name: 'Cichlid', family: 'Mermaid', element: 'Wind'},
  { name: 'Claire', family: 'Battle Angel', element: 'Fire' },
  { name: 'Clara', family: 'Pierret', element: 'Fire' },
  { name: 'Coco', family: 'Mage', element: 'Fire' },
  { name: 'Cogma', family: 'Imp', element: 'Fire' },
  { name: 'Colleen', family: 'Harpu', element: 'Fire' },
  { name: 'Conrad', family: 'Death Knight', element: 'Light' },
  { name: 'Copper', family: 'Living Armor', element: 'Wind' },
  { name: 'Cordelia', family: 'Blade Dancer', element: 'Wind' },
  { name: 'Covenant', family: 'Sniper Mk.I', element: 'Water' },
  { name: 'Craig', family: 'Slayer', element: 'Light' },
  { name: 'Craka', family: 'Hell Lady', element: 'Dark' },
  { name: 'Crane', family: 'Frankenstein', element: 'Wind' },
  { name: 'Crawler', family: 'Frankenstein', element: 'Dark' },
  { name: 'Dagora', family: 'Warbear', element: 'Water', index: 1 },
  { name: 'Dagorr', family: 'Bearman', element: 'Wind' },
  { name: 'Daharenos', family: 'Elemental', element: 'Water' },
  { name: 'Daniel', family: 'Sky Surfer', element: 'Light' },
  { name: 'Daphnis', family: 'Fairy King', element: 'Fire' },
  { name: 'Darion', family: 'Vagabond', element: 'Light', index: 1 },
  { name: 'Deborah', family: 'Rune Blacksmith', element: 'Dark' },
  { name: 'Decamaron', family: 'Salamander', element: 'Dark' },
  { name: 'Delphoi', family: 'Undine', element: 'Wind' },
  { name: 'Destiny', family: 'Battle Angel', element: 'Dark' },
  { name: 'Deva', family: 'Chakram Dancer', element: 'Light' },
  { name: 'Devinodon', family: 'Lizardman', element: 'Dark' },
  { name: 'DHALSIM', family: 'DHALSIM', element: 'Dark', index: 4 },
  { name: 'DHALSIM', family: 'DHALSIM', element: 'Light', index: 3 },
  { name: 'DHALSIM', family: 'DHALSIM', element: 'Wind', index: 2 },
  { name: 'DHALSIM', family: 'DHALSIM', element: 'Water', index: 0 },
  { name: 'DHALSIM', family: 'DHALSIM', element: 'Fire', index: 1 },
  { name: 'Diana', family: 'Unicorn', element: 'Wind' },
  { name: 'Diana', family: 'Unicorn', element: 'Wind', form: ' (Human)', index: 1 },
  { name: 'Dias', family: 'Death Knight', element: 'Dark' },
  { name: 'Dominic', family: 'Weapon Master', element: 'Wind' },
  { name: 'Dona', family: 'Penguin Knight', element: 'Light' },
  { name: 'Dongbaek', family: 'String Master', element: 'Light' },
  { name: 'Dorothy', family: 'Mage', element: 'Light' },
  { name: 'Douglas', family: 'Striker', element: 'Fire' },
  { name: 'Douman', family: 'Onmyouji', element: 'Dark' },
  { name: 'Dova', family: 'Harg', element: 'Light' },
  { name: 'Dover', family: 'Kobold Bomber', element: 'Light' },
  { name: 'Draco', family: 'Brownie Magician', element: 'Fire' },
  { name: 'Dragunov', family: 'Sniper Mk.I', element: 'Dark' },
  { name: 'Driller', family: 'Frankenstein', element: 'Light' },
  { name: 'Drogan', family: 'Inferno', element: 'Dark' },
  { name: 'Duamutef', family: 'Horus', element: 'Fire' },
  { name: 'Dusky', family: 'Jack-o’-lantern', element: 'Dark' },
  { name: 'Einheri', family: 'Giant Warrior', element: 'Light' },
  { name: 'Eintau', family: 'Minotauros', element: 'Wind' },
  { name: 'Eirgar', family: 'Vampire Lord', element: 'Dark' },
  { name: 'Eladriel', family: 'Archangel', element: 'Wind' },
  { name: 'Eleanor', family: 'Unicorn', element: 'Light' },
  { name: 'Eleanor', family: 'Unicorn', element: 'Light', form: ' (Human)', index: 1 },
  { name: 'Elena', family: 'Pudding Princess', element: 'Dark' },
  { name: 'Elenoa', family: 'Polar Queen', element: 'Light' },
  { name: 'Ella', family: 'Totemist', element: 'Light' },
  { name: 'Ellena', family: 'High Elemental', element: 'Water', index: 1 },
  { name: 'Ellin', family: 'Amazon', element: 'Water' },
  { name: 'Elpuria', family: 'Serpent', element: 'Light' },
  { name: 'Elsharion', family: 'Ifrit', element: 'Light' },
  { name: 'Elucia', family: 'Fairy', element: 'Water' , index: 1},
  { name: 'Eludain', family: 'Inferno', element: 'Light' },
  { name: 'Eludia', family: 'Phoenix', element: 'Light' },
  { name: 'Eluin', family: 'Elven Ranger', element: 'Water' },
  { name: 'Emily', family: 'Cannon Girl', element: 'Light' },
  { name: 'Emma', family: 'Neostone Agent', element: 'Water' },
  { name: 'Eredas', family: 'Sylph', element: 'Light' },
  { name: 'Ermeda', family: 'Serpent', element: 'Wind' },
  { name: 'Erwin', family: 'Elven Ranger', element: 'Wind' },
  { name: 'Eshir', family: 'Werewolf', element: 'Light', index: 1 },
  { name: 'Espresso Cookie', family: 'Espresso Cookie', element: 'Water', index: 0 },
  { name: 'Espresso Cookie', family: 'Espresso Cookie', element: 'Fire', index: 1 },
  { name: 'Espresso Cookie', family: 'Espresso Cookie', element: 'Wind', index: 2 },
  { name: 'Espresso Cookie', family: 'Espresso Cookie', element: 'Light', index: 3 },
  { name: 'Espresso Cookie', family: 'Espresso Cookie', element: 'Dark', index: 4 },
  { name: 'Ethna', family: 'Hell Lady', element: 'Wind' },
  { name: 'Eva', family: 'Pierret', element: 'Light' },
  { name: 'Fairo', family: 'Imp Champion', element: 'Fire' },
  { name: 'Fami', family: 'Magical Archer', element: 'Light' },
  { name: 'Fao', family: 'Serpent', element: 'Fire' },
  { name: 'Fedora', family: 'Death Knight', element: 'Water' },
  { name: 'Fei', family: 'Kung Fu Girl', element: 'Dark' },
  { name: 'Felleria', family: 'Dryad', element: 'Light' },
  { name: 'Feng Yan', family: 'Panda Warrior', element: 'Wind' },
  { name: 'Fermion', family: 'Archangel', element: 'Dark' },
  { name: 'Figaro', family: 'Joker', element: 'Light' },
  { name: 'Fran', family: 'Fairy Queen', element: 'Light' },
  { name: 'Fria', family: 'Sylphid', element: 'Fire' },
  { name: 'Frigate', family: 'Pirate Captain', element: 'Dark' },
  { name: 'Fuco', family: 'Lich', element: 'Wind' },
  { name: 'Fudge', family: 'Choco Knight', element: 'Light' },
  { name: 'Fuuki', family: 'Onimusha', element: 'Wind' },
  { name: 'Fynn', family: 'Imp', element: 'Water' },
  { name: 'Galleon', family: 'Pirate Captain', element: 'Water' },
  { name: 'Gamir', family: 'Hellhound', element: 'Wind' },
  { name: 'Ganache', family: 'Choco Knight', element: 'Water' },
  { name: 'Gangchun', family: 'Beast Hunter', element: 'Water' },
  { name: 'Ganymede', family: 'Fairy King', element: 'Wind' },
  { name: 'Garo', family: 'Ninja', element: 'Fire' },
  { name: 'Garoche', family: 'Werewolf', element: 'Fire', index: 1 },
  { name: 'Garok', family: 'Imp', element: 'Dark' },
  { name: 'Geldnir', family: 'Lightning Emperor', element: 'Light' },
  { name: 'Gemini', family: 'Brownie Magician', element: 'Light' },
  { name: 'Geoffrey', family: 'Viking', element: 'Fire' },
  { name: 'Giana', family: 'Oracle', element: 'Dark' },
  { name: 'Gildong', family: 'Taoist', element: 'Water' },
  { name: 'Gin', family: 'Ninja', element: 'Light' },
  { name: 'GingerBrave', family: 'GingerBrave', element: 'Wind' },
  { name: 'Gina', family: 'Mystic Witch', element: 'Dark', index: 1 },
  { name: 'Giou', family: 'Onmyouji', element: 'Wind' },
  { name: 'Giselle', family: 'Macaron Guard', element: 'Dark' },
  { name: 'Glinodon', family: 'Lizardman', element: 'Light' },
  { name: 'Gorgo', family: 'Warbear', element: 'Dark', index: 1 },
  { name: 'Granite', family: 'Battle Mammoth', element: 'Fire' },
  { name: 'Grego', family: 'Lich', element: 'Dark' },
  { name: 'Grogen', family: 'Dragon', element: 'Dark' },
  { name: 'Groggo', family: 'Golem', element: 'Light' },
  { name: 'Grotau', family: 'Minotauros', element: 'Light' },
  { name: 'Gruda', family: 'Bearman', element: 'Water' },
  { name: 'Guillaume', family: 'Phantom Thief', element: 'Dark' },
  { name: 'Gunpyeong', family: 'Taoist', element: 'Fire' },
  { name: 'Gurkha', family: 'Slayer', element: 'Dark' },
  { name: 'Haegang', family: 'Art Master', element: 'Water' },
  { name: 'Haken', family: 'Bearman', element: 'Dark' },
  { name: 'Halphas', family: 'Lich', element: 'Light' },
  { name: 'Han', family: 'Ninja', element: 'Dark' },
  { name: 'Hannah', family: 'Cow Girl', element: 'Wind' },
  { name: 'Hannam', family: 'Beast Hunter', element: 'Dark' },
  { name: 'Hanwul', family: 'Art Master', element: 'Light' },
  { name: 'Harmonia', family: 'Harp Magician', element: 'Fire' },
  { name: 'Hathor', family: 'Desert Queen', element: 'Wind' },
  { name: 'Hekerson', family: 'Poison Master', element: 'Light' },
  { name: 'Helena', family: 'Unicorn', element: 'Fire' },
  { name: 'Helena', family: 'Unicorn', element: 'Fire', form: ' (Human)', index: 1 },
  { name: 'Hellea', family: 'Harpy', element: 'Dark' },
  { name: 'Hemos', family: 'Grim Reaper', element: 'Water', index: 1 },
  { name: 'Herne', family: 'Dryad', element: 'Water' },
  { name: 'Herteit', family: 'Lightning Emperor', element: 'Dark' },
  { name: 'Hibiscus', family: 'Black Tea Bunny', element: 'Fire' },
  { name: 'Hina', family: 'Amazon', element: 'Wind' },
  { name: 'Hiro', family: 'Martial Artist', element: 'Light' },
  { name: 'Hiva', family: 'Grim Reaper', element: 'Wind', index: 1 },
  { name: 'Hollyberry Cookie', family: 'Hollyberry Cookie', element: 'Water', index: 0 },
  { name: 'Hollyberry Cookie', family: 'Hollyberry Cookie', element: 'Fire', index: 1 },
  { name: 'Hollyberry Cookie', family: 'Hollyberry Cookie', element: 'Wind', index: 2 },
  { name: 'Hollyberry Cookie', family: 'Hollyberry Cookie', element: 'Light', index: 3 },
  { name: 'Hollyberry Cookie', family: 'Hollyberry Cookie', element: 'Dark', index: 4 },
  { name: 'Hong Hua', family: 'Kung Fu Girl', element: 'Fire' },
  { name: 'Hongyeon', family: 'String Master', element: 'Fire' },
  { name: 'Hraesvelg', family: 'Barbaric King', element: 'Wind' },
  { name: 'Hrungnir', family: 'Barbaric King', element: 'Dark' },
  { name: 'Huan', family: 'Drunken Master', element: 'Wind' },
  { name: 'Huga', family: 'Viking', element: 'Water' },
  { name: 'Hwa', family: 'Rakshasa', element: 'Fire' },
  { name: 'Hwadam', family: 'Taoist', element: 'Light' },
  { name: 'Hwahee', family: 'Sky Dancer', element: 'Fire' },
  { name: 'Hyanes', family: 'Dryad', element: 'Dark' },
  { name: 'Icares', family: 'Sylphid', element: 'Dark' },
  { name: 'Icaru', family: 'Inugami', element: 'Water', index: 1 },
  { name: 'Icasha', family: 'Undine', element: 'Light' },
  { name: 'Igmanodon', family: 'Lizardman', element: 'Fire' },
  { name: 'Ignicus', family: 'Charger Shark', element: 'Fire' },
  { name: 'Illianna', family: 'Neostone Agent', element: 'Light' },
  { name: 'Imesety', family: 'Horus', element: 'Wind' },
  { name: 'Imp Champion', family: 'Imp Champion', element: 'Light' },
  { name: 'Iona', family: 'Epikion Priest', element: 'Light' },
  { name: 'Iris', family: 'Magic Knight', element: 'Light' },
  { name: 'Iron', family: 'Living Armor', element: 'Fire' },
  { name: 'Isabelle', family: 'Assassin', element: 'Dark' },
  { name: 'Isael', family: 'Succubus', element: 'Dark' },
  { name: 'Iselia', family: 'Fairy', element: 'Fire' , index: 1},
  { name: 'Isillen', family: 'Elven Ranger', element: 'Dark' },
  { name: 'Isis', family: 'Desert Queen', element: 'Light' },
  { name: 'Iunu', family: 'Anubis', element: 'Wind' },
  { name: 'Izaria', family: 'Succubus', element: 'Water' },
  { name: 'Jaara', family: 'Phoenix', element: 'Dark' },
  { name: 'Jackie', family: 'Martial Artist', element: 'Dark' },
  { name: 'Jackson', family: 'Sky Surfer', element: 'Dark' },
  { name: 'Jade', family: 'Macaron Guard', element: 'Wind' },
  { name: 'Jager', family: 'Dragon Knight', element: 'Light' },
  { name: 'Jamie', family: 'Bounty Hunter', element: 'Dark' },
  { name: 'Jasmine', family: 'Black Tea Bunny', element: 'Light' },
  { name: 'Jamire', family: 'Dragon', element: 'Wind' },
  { name: 'Janssen', family: 'Viking', element: 'Dark' },
  { name: 'Jansson', family: 'Viking', element: 'Light' },
  { name: 'Jarrett', family: 'Poison Master', element: 'Wind' },
  { name: 'Jean', family: 'Phantom Thief', element: 'Fire' },
  { name: 'Jeanne', family: 'Paladin', element: 'Light' },
  { name: 'Jeogun', family: 'Art Master', element: 'Fire' },
  { name: 'John', family: 'Sky Surfer', element: 'Fire' },
  { name: 'Jojo', family: 'Joker', element: 'Fire' },
  { name: 'Josephine', family: 'Paladin', element: 'Water' },
  { name: 'Jubelle', family: 'Vagabond', element: 'Dark', index: 1 },
  { name: 'Julianne', family: 'Vampire', element: 'Light' },
  { name: 'Julie', family: 'Pierret', element: 'Water' },
  { name: 'Julien', family: 'Phantom Thief', element: 'Wind' },
  { name: 'Jultan', family: 'Werewolf', element: 'Dark', index: 1 },
  { name: 'Jumaline', family: 'High Elemental', element: 'Dark', index: 1 },
  { name: 'Jun', family: 'Samurai', element: 'Fire' },
  { name: 'Juno', family: 'Oracle', element: 'Fire' },
  { name: 'Kabilla', family: 'Harpy', element: 'Light' },
  { name: 'Kacey', family: 'Pixie', element: 'Water', index: 1 },
  { name: 'Kahli', family: 'High Elemental', element: 'Fire', index: 1 },
  { name: 'Kahn', family: 'Griffon', element: 'Water', index: 1 },
  { name: "Kai'en", family: 'Vagabond', element: 'Fire', index: 1 },
  { name: 'Kaimann', family: 'Salamander', element: 'Water' },
  { name: 'Kaito', family: 'Samurai', element: 'Wind' },
  { name: 'Kaki', family: 'Onimusha', element: 'Fire' },
  { name: 'Kamatau', family: 'Minotauros', element: 'Dark' },
  { name: 'Kamiya', family: 'Nine-tailed Fox', element: 'Dark' },
  { name: 'Karakum', family: 'Mummy', element: 'Dark' },
  { name: 'Karl', family: 'Neostone Fighter', element: 'Dark' },
  { name: 'Karnal', family: 'Slayer', element: 'Fire' },
  { name: 'Kashmir', family: 'Striker', element: 'Wind' },
  { name: 'Katarina', family: 'Valkyrja', element: 'Wind' },
  { name: 'Kaz', family: 'Samurai', element: 'Water' },
  { name: 'Ken', family: 'Ken', element: 'Fire' },
  { name: 'Kernodon', family: 'Lizardman', element: 'Water' },
  { name: 'Khmun', family: 'Anubis', element: 'Fire' },
  { name: 'Kiki', family: 'Mage', element: 'Dark' },
  { name: 'Kinki', family: 'Onimusha', element: 'Light' },
  { name: 'Konamiya', family: 'Garuda', element: 'Water' },
  { name: 'Korona', family: 'Brownie Magician', element: 'Dark' },
  { name: 'Krakdon', family: 'Salamander', element: 'Fire' },
  { name: 'Kro', family: 'Inugami', element: 'Dark', index: 1 },
  { name: 'Kroa', family: 'Harg', element: 'Dark' },
  { name: 'Kugo', family: 'Golem', element: 'Fire' },
  { name: 'Kuhn', family: 'Golem', element: 'Water' },
  { name: 'Kumae', family: 'Yeti', element: 'Dark' },
  { name: 'Kumar', family: 'Beast Monk', element: 'Fire' },
  { name: 'Kuna', family: 'Penguin Knight', element: 'Dark' },
  { name: 'Kunda', family: 'Yeti', element: 'Water' },
  { name: 'Kungen', family: 'Bearman', element: 'Fire' },
  { name: 'Kunite', family: 'Gargoyle', element: 'Fire' },
  { name: 'Kyle', family: 'Poison Master', element: 'Water' },
  { name: 'Lagmaron', family: 'Chimera', element: 'Wind' },
  { name: 'Laika', family: 'Dragon Knight', element: 'Fire' },
  { name: 'Laima', family: 'Oracle', element: 'Light' },
  { name: 'Lala', family: 'Howl', element: 'Fire', index: 1 },
  { name: 'Lanett', family: 'Magic Knight', element: 'Dark' },
  { name: 'Lapis', family: 'Magic Knight', element: 'Water' },
  { name: 'Lariel', family: 'Blade Dancer', element: 'Water' },
  { name: 'Lavender', family: 'Black Tea Bunny', element: 'Dark' },
  { name: 'Leah', family: 'Blade Dancer', element: 'Light' },
  { name: 'Leo', family: 'Dragon Knight', element: 'Wind' },
  { name: 'Leona', family: 'Paladin', element: 'Dark' },
  { name: 'Lexy', family: 'Assassin', element: 'Fire' },
  { name: 'Liam', family: 'Weapon Master', element: 'Water' },
  { name: 'Liebli', family: 'Joker', element: 'Dark' },
  { name: 'Liesel', family: 'Vampire', element: 'Water' },
  { name: 'Linda', family: 'Mystic Witch', element: 'Light', index: 1 },
  { name: 'Lindermen', family: 'Garuda', element: 'Wind' },
  { name: 'Ling Ling', family: 'Kung Fu Girl', element: 'Wind' },
  { name: 'Lisa', family: 'Neostone Agent', element: 'Fire' },
  { name: 'Liu Mei', family: 'Kung Fu Girl', element: 'Light' },
  { name: 'Lo', family: 'Martial Artist', element: 'Wind' },
  { name: 'Logan', family: 'Neostone Fighter', element: 'Wind' },
  { name: 'Loque', family: 'Imp Champion', element: 'Dark' },
  { name: 'Lora', family: 'Occult Girl', element: 'Light' },
  { name: 'Loren', family: 'Cow Girl', element: 'Light' },
  { name: 'Louis', family: 'Phantom Thief', element: 'Light' },
  { name: 'Louise', family: 'Paladin', element: 'Wind' },
  { name: 'Luan', family: 'Martial Artist', element: 'Water' },
  { name: 'Lucas', family: 'Neostone Fighter', element: 'Light' },
  { name: 'Lucasha', family: 'Harpy', element: 'Fire' },
  { name: 'Lucia', family: 'Pudding Princess', element: 'Fire' },
  { name: 'Lucien', family: 'Elven Ranger', element: 'Light' },
  { name: 'Lucifer', family: 'Demon', element: 'Light' },
  { name: 'Ludo', family: 'Dice Magician', element: 'Fire' },
  { name: 'Luer', family: 'Phantom Thief', element: 'Water' },
  { name: 'Lukan', family: 'Salamander', element: 'Wind' },
  { name: 'Lulu', family: 'Howl', element: 'Water', index: 1 },
  { name: 'Lumirecia', family: 'Sylphid', element: 'Water' },
  { name: 'Luna', family: 'Pierret', element: 'Dark' },
  { name: 'Lupinus', family: 'Magic Knight', element: 'Wind' },
  { name: 'Lusha', family: 'Warbear', element: 'Light', index: 1 },
  { name: 'Lushen', family: 'Joker', element: 'Wind' },
  { name: 'Lydia', family: 'Polar Queen', element: 'Dark' },
  { name: 'Lyn', family: 'Amazon', element: 'Light' },
  { name: 'M. BISON', family: 'M. BISON', element: 'Dark', index: 4 },
  { name: 'M. BISON', family: 'M. BISON', element: 'Light', index: 3 },
  { name: 'M. BISON', family: 'M. BISON', element: 'Wind', index: 2 },
  { name: 'M. BISON', family: 'M. BISON', element: 'Water', index: 0 },
  { name: 'M. BISON', family: 'M. BISON', element: 'Fire', index: 1 },
  { name: 'Madeleine', family: 'Rune Blacksmith', element: 'Light' },
  { name: 'Madeleine Cookie', family: 'Madeleine Cookie', element: 'Water', index: 0 },
  { name: 'Madeleine Cookie', family: 'Madeleine Cookie', element: 'Fire', index: 1 },
  { name: 'Madeleine Cookie', family: 'Madeleine Cookie', element: 'Wind', index: 2 },
  { name: 'Madeleine Cookie', family: 'Madeleine Cookie', element: 'Light', index: 3 },
  { name: 'Madeleine Cookie', family: 'Madeleine Cookie', element: 'Dark', index: 4 },
  { name: 'Maggi', family: 'Golem', element: 'Dark' },
  { name: 'Magnum', family: 'Sniper Mk.I', element: 'Light' },
  { name: 'Malaka', family: 'Kobold Bomber', element: 'Water' },
  { name: 'Malite', family: 'Gargoyle', element: 'Wind' },
  { name: 'Manannan', family: 'Sea Emperor', element: 'Dark' },
  { name: 'Manon', family: 'Macaron Guard', element: 'Water' },
  { name: 'Mantura', family: 'Serpent', element: 'Dark' },
  { name: 'Manx', family: 'Hypnomeow', element: 'Fire' },
  { name: 'Mao', family: 'Drunken Master', element: 'Water' },
  { name: 'Mara', family: 'Amazon', element: 'Dark' },
  { name: 'Marble', family: 'Battle Mammoth', element: 'Light' },
  { name: 'Martina', family: 'Boomerang Warrior', element: 'Dark' },
  { name: 'Maruna', family: 'Boomerang Warrior', element: 'Fire' },
  { name: 'Masha', family: 'Beast Rider', element: 'Fire' },
  { name: 'Masha', family: 'Beast Rider', element: 'Fire', form: ' (Dismounted)', index: 1 },
  { name: 'Mav', family: 'Penguin Knight', element: 'Wind' },
  { name: 'Maximilian', family: 'Weapon Master', element: 'Dark' },
  { name: 'Maya', family: 'Totemist', element: 'Dark' },
  { name: 'Megan', family: 'Mystic Witch', element: 'Water', index: 1 },
  { name: 'Mei', family: 'Martial Cat', element: 'Fire', index: 1 },
  { name: 'Mei Hou Wang', family: 'Monkey King', element: 'Fire' },
  { name: 'Melissa', family: 'Chakram Dancer', element: 'Wind' },
  { name: 'Mellia', family: 'Dryad', element: 'Wind' },
  { name: 'Mephisto', family: 'Demon', element: 'Wind' },
  { name: 'Mi Ying', family: 'Panda Warrior', element: 'Dark' },
  { name: 'Michelle', family: 'Epikion Priest', element: 'Wind' },
  { name: 'Mihael', family: 'Sylphid', element: 'Light' },
  { name: 'Miho', family: 'Martial Cat', element: 'Dark', index: 1 },
  { name: 'Mihyang', family: 'Sky Dancer', element: 'Water' },
  { name: 'Mikene', family: 'Undine', element: 'Water' },
  { name: 'Miles', family: 'Sky Surfer', element: 'Water' },
  { name: 'Mimirr', family: 'Barbaric King', element: 'Light' },
  { name: 'Mina', family: 'Martial Cat', element: 'Water', index: 1 },
  { name: 'Minato', family: 'Shadowcaster', element: 'Water' },
  { name: 'Miriam', family: 'Rune Blacksmith', element: 'Fire' },
  { name: 'Mirinae', family: 'String Master', element: 'Dark' },
  { name: 'Misty', family: 'Jack-o’-lantern', element: 'Light' },
  { name: 'Mo Long', family: 'Panda Warrior', element: 'Water' },
  { name: 'Molly', family: 'Mermaid', element: 'Light' },
  { name: 'Momo', family: 'Mage', element: 'Wind' },
  { name: 'Monte', family: 'Dice Magician', element: 'Dark' },
  { name: 'Mookwol', family: 'Art Master', element: 'Dark' },
  { name: 'Moore', family: 'Striker', element: 'Water' },
  { name: 'Moria', family: 'High Elemental', element: 'Wind', index: 1 },
  { name: 'Morris', family: 'Dice Magician', element: 'Wind' },
  { name: 'Naki', family: 'Penguin Knight', element: 'Fire' },
  { name: 'Namib', family: 'Mummy', element: 'Wind' },
  { name: 'Nana', family: 'Mage', element: 'Water' },
  { name: 'Nangrim', family: 'Beast Hunter', element: 'Fire' },
  { name: 'Naomi', family: 'Martial Cat', element: 'Wind', index: 1 },
  { name: 'Narsha', family: 'Beast Rider', element: 'Light', form: ' (Dismounted)', index: 1 },
  { name: 'Natalie', family: 'Assassin', element: 'Light' },
  { name: 'Neal', family: 'Fairy', element: 'Light' , index: 1},
  { name: 'Nebelung', family: 'Hypnomeow', element: 'Wind' },
  { name: 'Nephthys', family: 'Desert Queen', element: 'Dark' },
  { name: 'Nickel', family: 'Living Armor', element: 'Water' },
  { name: 'Nicki', family: 'Occult Girl', element: 'Dark' },
  { name: 'Nigong', family: 'Pioneer', element: 'Light' },
  { name: 'Nisha', family: 'Dryad', element: 'Fire' },
  { name: 'Nora', family: 'Totemist', element: 'Fire' },
  { name: 'Nubia', family: 'Mummy', element: 'Water' },
  { name: 'Nyx', family: 'Fairy King', element: 'Dark' },
  { name: 'Oberon', family: 'Fairy King', element: 'Light' },
  { name: 'Odin', family: 'Lightning Emperor', element: 'Wind' },
  { name: 'Okeanos', family: 'Sea Emperor', element: 'Fire' },
  { name: 'Oliver', family: 'Sky Surfer', element: 'Wind' },
  { name: 'Olivia', family: 'Neostone Agent', element: 'Wind' },
  { name: 'Olivine', family: 'Battle Mammoth', element: 'Wind' },
  { name: 'Ongyouki', family: 'Onimusha', element: 'Dark' },
  { name: 'Onyx', family: 'Gargoyle', element: 'Dark' },
  { name: 'Ophilia', family: 'Paladin', element: 'Fire' },
  { name: 'Orion', family: 'Brownie Magician', element: 'Water' },
  { name: 'Orochi', family: 'Ninja', element: 'Wind' },
  { name: 'Pang', family: 'Rakshasa', element: 'Light' },
  { name: 'Pater', family: 'Druid', element: 'Dark' },
  { name: 'Pater', family: 'Druid', element: 'Dark', form: ' (Beast)', index: 1 },
  { name: 'Pavé', family: 'Choco Knight', element: 'Fire' },
  { name: 'Perna', family: 'Phoenix', element: 'Fire' },
  { name: 'Phenaka', family: 'Gargoyle', element: 'Light' },
  { name: 'Pigma', family: 'Imp Champion', element: 'Wind' },
  { name: 'Platy', family: 'Mermaid', element: 'Fire' },
  { name: 'Pontos', family: 'Sea Emperor', element: 'Light' },
  { name: 'Poseidon', family: 'Sea Emperor', element: 'Water' },
  { name: 'Praha', family: 'Oracle', element: 'Water' },
  { name: 'Praline ', family: 'Choco Knight', element: 'Wind' },
  { name: 'Prilea', family: 'Harpy', element: 'Wind' },
  { name: 'Priz', family: 'Elemental', element: 'Light' },
  { name: 'Prom', family: 'Grim Reaper', element: 'Light', index: 1 },
  { name: 'Psamathe', family: 'Fairy King', element: 'Water' },
  { name: 'Pungbaek', family: 'Pioneer', element: 'Wind' },
  { name: 'Pure Vanilla Cookie', family: 'Pure Vanilla Cookie', element: 'Water', index: 0 },
  { name: 'Pure Vanilla Cookie', family: 'Pure Vanilla Cookie', element: 'Fire', index: 1 },
  { name: 'Pure Vanilla Cookie', family: 'Pure Vanilla Cookie', element: 'Wind', index: 2 },
  { name: 'Pure Vanilla Cookie', family: 'Pure Vanilla Cookie', element: 'Light', index: 3 },
  { name: 'Pure Vanilla Cookie', family: 'Pure Vanilla Cookie', element: 'Dark', index: 4 },
  { name: 'Purian', family: 'Inferno', element: 'Water' },
  { name: 'Qebehsenuef', family: 'Horus', element: 'Water' },
  { name: 'Qitian Dasheng', family: 'Monkey King', element: 'Light' },
  { name: 'Racuni', family: 'Harg', element: 'Fire' },
  { name: 'Ragdoll', family: 'Dragon Knight', element: 'Dark' },
  { name: 'Ragion', family: 'Golem', element: 'Wind' },
  { name: 'Rahul', family: 'Beast Monk', element: 'Dark' },
  { name: 'Rakaja', family: 'Yeti', element: 'Wind' },
  { name: 'Rakan', family: 'Chimera', element: 'Fire' },
  { name: 'Raki', family: 'Hell Lady', element: 'Fire' },
  { name: 'Ralph', family: 'Imp', element: 'Wind' },
  { name: 'Ramagos', family: 'Warbear', element: 'Wind', index: 1 },
  { name: 'Ramahan', family: 'Inugami', element: 'Wind', index: 1 },
  { name: 'Ramira', family: 'Harpy', element: 'Water' },
  { name: 'Ran', family: 'Rakshasa', element: 'Dark' },
  { name: 'Randy', family: 'Bounty Hunter', element: 'Fire' },
  { name: 'Raoq', family: 'Inugami', element: 'Fire', index: 1 },
  { name: 'Rasheed', family: 'Epikion Priest', element: 'Dark' },
  { name: 'Raviti', family: 'Harg', element: 'Wind' },
  { name: 'Rebecca', family: 'Mystic Witch', element: 'Fire', index: 1 },
  { name: 'Remy', family: 'Harg', element: 'Water' },
  { name: 'Ren', family: 'Shadowcaster', element: 'Fire' },
  { name: 'Reno', family: 'Dice Magician', element: 'Water' },
  { name: 'Rica', family: 'Occult Girl', element: 'Fire' },
  { name: 'Rigel', family: 'Lich', element: 'Water' },
  { name: 'Riley', family: 'Totemist', element: 'Wind' },
  { name: 'Rina', family: 'Epikion Priest', element: 'Water' },
  { name: 'Ritesh', family: 'Beast Monk', element: 'Wind' },
  { name: 'Ritsu', family: 'Shadowcaster', element: 'Dark' },
  { name: 'Rizak', family: 'Garuda', element: 'Dark' },
  { name: 'Robo-E65', family: 'Robo', element: 'Light' },
  { name: 'Robo-F29', family: 'Robo', element: 'Dark' },
  { name: 'Robo-G92', family: 'Robo', element: 'Wind' },
  { name: 'Robo-P27', family: 'Robo', element: 'Fire' },
  { name: 'Robo-R40', family: 'Robo', element: 'Water' },
  { name: 'Roger', family: 'Bounty Hunter', element: 'Wind' },
  { name: 'Roid', family: 'Vagabond', element: 'Wind', index: 1 },
  { name: 'Rosemary', family: 'Black Tea Bunny', element: 'Water' },
  { name: 'Rumicus', family: 'Charger Shark', element: 'Light' },
  { name: 'Ryan', family: 'Neostone Fighter', element: 'Water' },
  { name: 'RYU', family: 'RYU', element: 'Dark', index: 4 },
  { name: 'RYU', family: 'RYU', element: 'Light', index: 3 },
  { name: 'RYU', family: 'RYU', element: 'Wind', index: 2 },
  { name: 'RYU', family: 'RYU', element: 'Water', index: 0 },
  { name: 'RYU', family: 'RYU', element: 'Fire', index: 1 },
  { name: 'Sabrina', family: 'Boomerang Warrior', element: 'Water' },
  { name: 'Sagar', family: 'Slayer', element: 'Wind' },
  { name: 'Sahara', family: 'Mummy', element: 'Light' },
  { name: 'Sath', family: 'Grim Reaper', element: 'Fire', index: 1 },
  { name: 'Savannah', family: 'Beast Rider', element: 'Wind' },
  { name: 'Savannah', family: 'Beast Rider', element: 'Wind', form: ' (Dismounted)', index: 1 },
  { name: 'Scarlett', family: 'Cannon Girl', element: 'Fire' },
  { name: 'Seal', family: 'Harpu', element: 'Wind' },
  { name: 'Seara', family: 'Oracle', element: 'Wind' },
  { name: 'Seimei', family: 'Onmyouji', element: 'Light' },
  { name: 'Sekhmet', family: 'Desert Queen', element: 'Fire' },
  { name: 'Selena', family: 'Succubus', element: 'Wind' },
  { name: 'Sera', family: 'Cow Girl', element: 'Water' },
  { name: 'Seren', family: 'Harpu', element: 'Dark' },
  { name: 'Shailoq', family: 'Serpent', element: 'Water' },
  { name: 'Shaina', family: 'Chakram Dancer', element: 'Fire' },
  { name: 'Shakan', family: 'Werewolf', element: 'Wind', index: 1 },
  { name: 'Shamann', family: 'Griffon', element: 'Light', index: 1 },
  { name: 'Shamar', family: 'Hellhound', element: 'Light' },
  { name: 'Shan', family: 'Chimera', element: 'Light' },
  { name: 'Shannon', family: 'Pixie', element: 'Wind', index: 1 },
  { name: 'Sharman', family: 'Salamander', element: 'Light' },
  { name: 'Sharron', family: 'Magical Archer', element: 'Water' },
  { name: 'Shazam', family: 'Beast Monk', element: 'Light' },
  { name: 'Shi Hou', family: 'Monkey King', element: 'Water' },
  { name: 'Shihwa', family: 'Nine-tailed Fox', element: 'Fire' },
  { name: 'Shimitae', family: 'Sylph', element: 'Wind' },
  { name: 'Shizuka', family: 'Onmyouji', element: 'Water' },
  { name: 'Shren', family: 'High Elemental', element: 'Light', index: 1 },
  { name: 'Shumar', family: 'Hellhound', element: 'Dark' },
  { name: 'Shun', family: 'Shadowcaster', element: 'Light' },
  { name: 'Shushu', family: 'Howl', element: 'Light', index: 1 },
  { name: 'Sia', family: 'Harpu', element: 'Light' },
  { name: 'Siamese', family: 'Hypnomeow', element: 'Light' },
  { name: 'Sian', family: 'Joker', element: 'Water' },
  { name: 'Sieq', family: 'Hellhound', element: 'Fire' },
  { name: 'Sige', family: 'Samurai', element: 'Dark' },
  { name: 'Sigmarus', family: 'Phoenix', element: 'Water' },
  { name: 'Silia', family: 'Mystic Witch', element: 'Wind', index: 1 },
  { name: 'Silver', family: 'Living Armor', element: 'Light' },
  { name: 'Sin', family: 'Martial Artist', element: 'Fire' },
  { name: 'Sisroo', family: 'Harpu', element: 'Water' },
  { name: 'Skogul', family: 'Giant Warrior', element: 'Wind' },
  { name: 'Smokey', family: 'Jack-o’-lantern', element: 'Fire' },
  { name: 'Soha', family: 'Nine-tailed Fox', element: 'Water' },
  { name: 'Son Zhang Lao', family: 'Monkey King', element: 'Dark' },
  { name: 'Songseol', family: 'String Master', element: 'Water' },
  { name: 'Sonia', family: 'Battle Angel', element: 'Wind' },
  { name: 'Sonnet', family: 'Harp Magician', element: 'Water' },
  { name: 'Sonora', family: 'Mummy', element: 'Fire' },
  { name: 'Sophia', family: 'Pierret', element: 'Wind' },
  { name: 'Sorin', family: 'Fairy', element: 'Dark' , index: 1},
  { name: 'Spectra', family: 'Griffon', element: 'Fire', index: 1 },
  { name: 'Stella', family: 'Assassin', element: 'Water' },
  { name: 'Su', family: 'Rakshasa', element: 'Water' },
  { name: 'Suiki', family: 'Onimusha', element: 'Water' },
  { name: 'Suri', family: 'Beast Hunter', element: 'Wind' },
  { name: 'Surtr', family: 'Barbaric King', element: 'Fire' },
  { name: 'Susan', family: 'Rune Blacksmith', element: 'Water' },
  { name: 'Susano', family: 'Ninja', element: 'Water' },
  { name: 'Sylvia', family: 'Neostone Agent', element: 'Dark' },
  { name: 'Tablo', family: 'Dice Magician', element: 'Light' },
  { name: 'Tagaros', family: 'Inferno', element: 'Fire' },
  { name: 'Taharus', family: 'Elemental', element: 'Wind' },
  { name: 'Talc', family: 'Battle Mammoth', element: 'Water' },
  { name: 'Talia', family: 'Chakram Dancer', element: 'Water' },
  { name: 'Talisman', family: 'Striker', element: 'Light' },
  { name: 'Tantra', family: 'Yeti', element: 'Fire' },
  { name: 'Tanya', family: 'Assassin', element: 'Wind' },
  { name: 'Tanzaite', family: 'Gargoyle', element: 'Water' },
  { name: 'Taor', family: 'Chimera', element: 'Water' },
  { name: 'Taranys', family: 'Druid', element: 'Wind' },
  { name: 'Taranys', family: 'Druid', element: 'Wind', form: ' (Beast)', index: 1 },
  { name: 'Tarq', family: 'Hellhound', element: 'Water' },
  { name: 'Taru', family: 'Imp', element: 'Light' },
  { name: 'Tatu', family: 'Pixie', element: 'Fire', index: 1 },
  { name: 'Taurus', family: 'Kobold Bomber', element: 'Wind' },
  { name: 'Teon', family: 'Garuda', element: 'Light' },
  { name: 'Tesarion', family: 'Ifrit', element: 'Fire' },
  { name: 'Teshar', family: 'Phoenix', element: 'Wind' },
  { name: 'Tetra', family: 'Mermaid', element: 'Water' },
  { name: 'Thebae', family: 'Anubis', element: 'Dark' },
  { name: 'Theomars', family: 'Ifrit', element: 'Water' },
  { name: 'Thrain', family: 'Grim Reaper', element: 'Dark', index: 1 },
  { name: 'Tian Lang', family: 'Panda Warrior', element: 'Light' },
  { name: 'Tiana', family: 'Polar Queen', element: 'Wind' },
  { name: 'Tien Qin', family: 'Drunken Master', element: 'Light' },
  { name: 'Tilasha', family: 'Undine', element: 'Dark' },
  { name: 'Todd', family: 'Poison Master', element: 'Fire' },
  { name: 'Toma', family: 'Penguin Knight', element: 'Water' },
  { name: 'Tomoe', family: 'Onmyouji', element: 'Fire' },
  { name: 'Tosi', family: 'Samurai', element: 'Light' },
  { name: 'Tractor', family: 'Frankenstein', element: 'Water' },
  { name: 'Trasar', family: 'Giant Warrior', element: 'Dark' },
  { name: 'Trevor', family: 'Neostone Fighter', element: 'Fire' },
  { name: 'Triana', family: 'Harp Magician', element: 'Wind' },
  { name: 'Trinity', family: 'Valkyrja', element: 'Dark' },
  { name: 'Triton', family: 'Sea Emperor', element: 'Wind' },
  { name: 'Truffle', family: 'Choco Knight', element: 'Dark' },
  { name: 'Tyron', family: 'Sylph', element: 'Water' },
  { name: 'Ursha', family: 'Warbear', element: 'Fire', index: 1 },
  { name: 'Urtau', family: 'Minotauros', element: 'Water' },
  { name: 'Valantis', family: 'Druid', element: 'Light' },
  { name: 'Valantis', family: 'Druid', element: 'Light', form: ' (Beast)', index: 1 },
  { name: 'Vancliffe', family: 'Striker', element: 'Dark' },
  { name: 'Vanessa', family: 'Valkyrja', element: 'Fire' },
  { name: 'Varus', family: 'Griffon', element: 'Dark', index: 1 },
  { name: 'Velajuel', family: 'Archangel', element: 'Fire' },
  { name: 'Velfinodon', family: 'Lizardman', element: 'Wind' },
  { name: 'Verad', family: 'Dragon', element: 'Water' },
  { name: 'Verdehile', family: 'Vampire', element: 'Fire' },
  { name: 'Vereesa', family: 'Blade Dancer', element: 'Dark' },
  { name: 'Veromos', family: 'Ifrit', element: 'Dark' },
  { name: 'Veronica', family: 'Battle Angel', element: 'Light' },
  { name: 'Vidurr', family: 'Giant Warrior', element: 'Fire' },
  { name: 'Vigor', family: 'Werewolf', element: 'Water', index: 1 },
  { name: 'Vivachel', family: 'Harp Magician', element: 'Dark' },
  { name: 'Walkers', family: 'Bounty Hunter', element: 'Light' },
  { name: 'Walter', family: 'Viking', element: 'Wind' },
  { name: 'Wayne', family: 'Bounty Hunter', element: 'Water' },
  { name: 'Wedjat', family: 'Horus', element: 'Light' },
  { name: 'Wei Shin', family: 'Drunken Master', element: 'Dark' },
  { name: 'Windy', family: 'Jack-o’-lantern', element: 'Wind' },
  { name: 'Wolyung', family: 'Sky Dancer', element: 'Dark' },
  { name: 'Woochi', family: 'Taoist', element: 'Wind' },
  { name: 'Woonhak', family: 'Taoist', element: 'Dark' },
  { name: 'Woonsa', family: 'Pioneer', element: 'Dark' },
  { name: 'Woosa', family: 'Pioneer', element: 'Water' },
  { name: 'Xiana', family: 'Beast Rider', element: 'Dark', form: ' (Dismounted)', index: 1 },
  { name: 'Xiao Chun', family: 'Drunken Master', element: 'Fire' },
  { name: 'Xiao Lin', family: 'Kung Fu Girl', element: 'Water' },
  { name: 'Xiao Ling', family: 'Martial Cat', element: 'Light', index: 1 },
  { name: 'Xing Zhe', family: 'Monkey King', element: 'Wind' },
  { name: 'Xiong Fei', family: 'Panda Warrior', element: 'Fire' },
  { name: 'Yaku', family: 'Imp Champion', element: 'Water' },
  { name: 'Yen', family: 'Rakshasa', element: 'Wind' },
  { name: 'Yeonhong', family: 'Sky Dancer', element: 'Light' },
  { name: 'Yeonhwa', family: 'String Master', element: 'Wind' },
  { name: 'Zaiross', family: 'Dragon', element: 'Fire' },
  { name: 'Zen', family: 'Shadowcaster', element: 'Wind' },
  { name: 'Zenobia', family: 'Boomerang Warrior', element: 'Wind' },
  { name: 'Zephicus', family: 'Charger Shark', element: 'Wind' },
  { name: 'Zerath', family: 'Dragon', element: 'Light' },
  { name: 'Zeratu', family: 'Chimera', element: 'Dark' },
  { name: 'Zibrolta', family: 'Kobold Bomber', element: 'Fire' },
  { name: 'Zinc', family: 'Living Armor', element: 'Dark' },
]
// const monsList  = [
//   { title: 'The Shawshank Redemption', year: 1994 },
//   { title: 'The Dark Knight', year: 2008 },
//   { title: 'Pulp Fiction', year: 1994 },
// ]
